server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Gateway, ecommerce-gateway
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/pedidos/**
              filters:
                - AddRequestHeader=X-Gateway-Source, api-gateway
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/pagos/**
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/api/productos/**
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventario/**
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/carrito/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
