spring.application.name=usuario-service
server.port=8086

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3311/usuario_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:desarrollador}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_seguro_123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.enabled=false

usuario.service.url=${USUARIO_SERVICE_URL:http://localhost:8086}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8083}
