# ===== Identidad del servicio =====
spring.application.name=eureka-server

# ===== Puerto del servidor =====
server.port=8761

# ===== Configuración Eureka =====
# Este SERVIDOR no se registra a sí mismo (es el registro central)
eureka.client.register-with-eureka=false
# Y no necesita descargar el registro porque ÉL ES el registro
eureka.client.fetch-registry=false

# Para entornos de desarrollo: deshabilita el modo de auto-protección
# (En producción se deja en true para evitar borrar servicios por fallos de red)
eureka.server.enable-self-preservation=false